
alias cap='nocorrect cap'
alias man='nocorrect man'
alias tree='nocorrect tree'
alias thor='nocorrect thor'
alias mysql='nocorrect mysql'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias ebuild='nocorrect ebuild'
alias hpodder='nocorrect hpodder'
alias pyload='nocorrect pyload'
